// Sample data for initial display
// This will be replaced by real data from the database

export const sampleProjects = [
  {
    id: '1',
    title: 'LenoSol SL',
    slug: 'lenosolsl',
    type: 'public' as const,
    category: 'fintech',
    short_description: 'A comprehensive financial technology solution for Sierra Leone, enabling digital payments and financial inclusion.',
    live_url: 'https://lenosolsl.vercel.app/',
    github_repo_url: 'https://github.com/Eager1337',
    thumbnail_url: '',
    demo_type: 'production' as const,
    stack: ['React', 'Node.js', 'PostgreSQL', 'Stripe'],
    is_featured: true,
    visibility_level: 'public_teaser',
  },
  {
    id: '2',
    title: 'FintechBeaver',
    slug: 'fintechbeaver',
    type: 'public' as const,
    category: 'fintech',
    short_description: 'Modern fintech platform with secure payment processing and financial analytics dashboard.',
    live_url: 'https://fintechbeaver.vercel.app/',
    github_repo_url: 'https://github.com/Eager1337',
    thumbnail_url: '',
    demo_type: 'production' as const,
    stack: ['Next.js', 'TypeScript', 'Tailwind', 'Supabase'],
    is_featured: true,
    visibility_level: 'public_teaser',
  },
  {
    id: '3',
    title: 'Palm Ledger PWA',
    slug: 'palm-ledger',
    type: 'public' as const,
    category: 'fintech',
    short_description: 'Progressive web app for personal finance management with offline capabilities.',
    live_url: 'https://v0-palm-ledger-pwa-ui.vercel.app/',
    github_repo_url: '',
    thumbnail_url: '',
    demo_type: 'production' as const,
    stack: ['React', 'PWA', 'IndexedDB', 'Chart.js'],
    is_featured: false,
    visibility_level: 'public_teaser',
  },
  {
    id: '4',
    title: 'SalonePay',
    slug: 'salonepay',
    type: 'public' as const,
    category: 'fintech',
    short_description: 'Payment gateway and mobile money solution for Sierra Leone market.',
    live_url: 'https://salonepay.vercel.app/',
    github_repo_url: '',
    thumbnail_url: '',
    demo_type: 'production' as const,
    stack: ['React', 'Express', 'MongoDB', 'Mobile Money API'],
    is_featured: true,
    visibility_level: 'public_teaser',
  },
  {
    id: '5',
    title: 'Sacred Path',
    slug: 'sacred-path',
    type: 'public' as const,
    category: 'web',
    short_description: 'Spiritual wellness and meditation platform with guided sessions.',
    live_url: 'https://sacredpath.lovable.app/',
    github_repo_url: '',
    thumbnail_url: '',
    demo_type: 'production' as const,
    stack: ['React', 'Tailwind', 'Framer Motion'],
    is_featured: false,
    visibility_level: 'public_teaser',
  },
  {
    id: '6',
    title: 'SL Health',
    slug: 'sl-health',
    type: 'public' as const,
    category: 'web',
    short_description: 'Healthcare information and appointment booking platform for Sierra Leone.',
    live_url: 'https://slhealth.lovable.app/',
    github_repo_url: '',
    thumbnail_url: '',
    demo_type: 'production' as const,
    stack: ['React', 'Supabase', 'Tailwind', 'Maps API'],
    is_featured: true,
    visibility_level: 'public_teaser',
  },
  {
    id: '7',
    title: 'SkillBridge SL',
    slug: 'skillbridge-sl',
    type: 'public' as const,
    category: 'web',
    short_description: 'Skills training and job matching platform connecting talent with opportunities.',
    live_url: 'https://v0-skill-bridgesl.vercel.app/',
    github_repo_url: '',
    thumbnail_url: '',
    demo_type: 'production' as const,
    stack: ['Next.js', 'Prisma', 'PostgreSQL'],
    is_featured: false,
    visibility_level: 'public_teaser',
  },
  {
    id: '8',
    title: 'Enterprise Analytics',
    slug: 'enterprise-analytics',
    type: 'private' as const,
    category: 'internal',
    short_description: 'Internal analytics and reporting system for enterprise clients.',
    live_url: '',
    github_repo_url: '',
    thumbnail_url: '',
    demo_type: 'restricted' as const,
    stack: ['React', 'D3.js', 'Node.js', 'PostgreSQL'],
    is_featured: false,
    visibility_level: 'investor',
  },
];

export const sampleSkills = [
  { name: 'React', category: 'Frontend', proficiency: 95 },
  { name: 'TypeScript', category: 'Languages', proficiency: 90 },
  { name: 'Node.js', category: 'Backend', proficiency: 88 },
  { name: 'Next.js', category: 'Frontend', proficiency: 85 },
  { name: 'Python', category: 'Languages', proficiency: 82 },
  { name: 'PostgreSQL', category: 'Database', proficiency: 85 },
  { name: 'Tailwind CSS', category: 'Frontend', proficiency: 95 },
  { name: 'Supabase', category: 'Backend', proficiency: 90 },
  { name: 'Framer Motion', category: 'Frontend', proficiency: 85 },
  { name: 'Git', category: 'Tools', proficiency: 90 },
  { name: 'Docker', category: 'DevOps', proficiency: 75 },
  { name: 'AWS', category: 'Cloud', proficiency: 70 },
  { name: 'Figma', category: 'Design', proficiency: 80 },
  { name: 'Premiere Pro', category: 'Video', proficiency: 85 },
  { name: 'After Effects', category: 'Animation', proficiency: 80 },
  { name: 'Photoshop', category: 'Design', proficiency: 85 },
  { name: 'Cybersecurity', category: 'Security', proficiency: 75 },
];

export const sampleServices = [
  {
    id: '1',
    title: 'Full-Stack Web Development',
    description: 'End-to-end web application development using modern technologies.',
    icon: 'code',
    features: ['React/Next.js', 'Node.js/Express', 'PostgreSQL/MongoDB', 'API Development'],
  },
  {
    id: '2',
    title: 'Fintech Solutions',
    description: 'Secure payment systems, mobile money integration, and financial platforms.',
    icon: 'wallet',
    features: ['Payment Gateways', 'Mobile Money', 'Financial Analytics', 'Compliance'],
  },
  {
    id: '3',
    title: 'UI/UX Design',
    description: 'Beautiful, intuitive interfaces that users love.',
    icon: 'palette',
    features: ['User Research', 'Wireframing', 'Prototyping', 'Design Systems'],
  },
  {
    id: '4',
    title: 'Video Editing & Animation',
    description: 'Professional video production and motion graphics.',
    icon: 'video',
    features: ['Video Editing', 'Motion Graphics', 'Color Grading', 'Sound Design'],
  },
  {
    id: '5',
    title: 'Mobile App Development',
    description: 'Cross-platform mobile applications for iOS and Android.',
    icon: 'smartphone',
    features: ['React Native', 'Flutter', 'PWA', 'App Store Deployment'],
  },
  {
    id: '6',
    title: 'Cybersecurity Consulting',
    description: 'Security audits, vulnerability assessments, and best practices.',
    icon: 'shield',
    features: ['Security Audits', 'Penetration Testing', 'Compliance', 'Training'],
  },
];

export const profileData = {
  name: 'EagerBeaver',
  role: 'Full-stack Developer / Product Builder',
  bio: 'A passionate technologist with a focus on building impactful solutions. I combine technical expertise with product thinking to create systems that matter. Based in Freetown, Sierra Leone.',
  education: 'Limkokwing University, Freetown',
  location: 'Freetown, Sierra Leone',
  phone: '033695803',
  email: 'ebeaver091@gmail.com',
  github_url: 'https://github.com/Eager1337',
};
